### PR TITLE
Fix logic from PR #2

### PR DESCRIPTION
**Pull request by aripollak**

### CODE REVIEW

**Comment by technicalpickles** [comment]
What is wrong with #2 exactly?

**Comment by aripollak** [comment]
The environment variable was being treated as the exact opposite of what it says :grimacing:

**Comment by aripollak** [comment]
Ping! Anyone still monitoring this?

**Comment by timabbott** [comment]
Hi @aripollak, looks like nobody ~nobody was when you submitted it.  It seems to me that your fix is good; I have to run right now but can merge when I get back to a computer.

Thanks for fixing this!

**Comment by timabbott** [comment]
Merged, thanks @aripollak, and sorry for the very long delay merging this!  I must have missed the discussion in September.

**Pull request closed without merging**
